name: ${PROD_PROJECT_NAME}
services:
  wordpress:
    ports:
      - "80"
    environment:
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/wordpress_db_password
    secrets:
      - wordpress_db_password
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    
  db:
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    networks:
       wordpress_network:
         ipv4_address: 192.168.1.5
    secrets:
      - mysql_root_password
      - mysql_password

networks:
  wordpress_network:
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1

secrets:
  wordpress_db_password:
    file: ./secrets/wordpress_db_password.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt
  mysql_password:
    file: ./secrets/mysql_password.txt

volumes:
  db_data:
    labels:
      com.example.environment: "Production"
