apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: hello-world
spec:
  selector:
    app: hello-world
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

# Services provide a stable endpoint for accessing a set of pods